import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
// import { auth } from "@/auth";
// import LogoutButton from "./(logged-in)/auth-components";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextAuth Application",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const session = await auth();

  return (
    <html lang="en">
      <body className={ `${ geistSans.variable } ${ geistMono.variable } antialiased` }>
        <>
          {/* <div>{ session?.user?.email ?
            <div><LogoutButton /> { session?.user?.email }</div>
            : "There is no session for the user" }</div> */}
          <Toaster />
          { children }
        </>
      </body>
    </html>
  );
}
